### ISSUE TITLE
请问一下原始的工程代码可以上传吗？

### ISSUE THREAD

**Issue by IamHuskar** [Neiven1/CM3_on_7010#1]
这个readme里面还缺一些信息哦

**Comment by IamHuskar** [comment]
跪求工程文件，或者更详细的带图readme.md。谢谢楼主

**Comment by Neiven1** [comment]
IamHuskar
        您好！我已收到您的邮件。
        附件是实验的解说视频，有详细的工程建立流程，工程文件暂不方便上传。
        


2024-4-23
| |
15901451390
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年4月22日 15:04 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | Re: [Neiven1/CM3_on_7010] 请问一下原始的工程代码可以上传吗？ (Issue #1) |

跪求工程文件，或者更详细的带图readme.md。谢谢楼主

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| CM3软核移植_XS22033006_郭彤彤.mp4 |
| |
| (430.9MB,2024年5月8日 14:11 到期) |
| |
| 下载 |
| |
| |

**Comment by IamHuskar** [comment]
> IamHuskar 您好！我已收到您的邮件。 附件是实验的解说视频，有详细的工程建立流程，工程文件暂不方便上传。 2024-4-23 | | 15901451390 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年4月22日 15:04 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> | | 主题 | Re: [Neiven1/CM3_on_7010] 请问一下原始的工程代码可以上传吗？ (Issue #1) | 跪求工程文件，或者更详细的带图readme.md。谢谢楼主 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 从 网易邮箱大师 发来的云附件 | | | | | | | | | CM3软核移植_XS22033006_郭彤彤.mp4 | | | | (430.9MB,2024年5月8日 14:11 到期) | | | | 下载 | | | | |

你好。非常感谢您的回复。网易邮箱大师的云附件github上似乎无法下载和收到。
能否麻烦您发送到 iamhuskar@qq.com 
非常谢谢您了。
